version: '3.9'

services:
  xm_app:
    env_file:
      - .env
    container_name: xm_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    expose:
      - "1000"
    ports:
      - "1000:1000"
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:14.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./deploy/sql:/docker-entrypoint-initdb.d
volumes:
  pg-data:
